[theme]
primaryColor = "#1DB954"         # Spotify's green color
backgroundColor = "#212121"      # Spotify's dark background color
secondaryBackgroundColor = "#282828"  # Darker shade for secondary backgrounds
textColor = "#FFFFFF"            # White text
font = "sans serif"              # Default font
